"""add fields and tables for rich projects

Revision ID: 36df1f56cb9e
Revises: 5a9269d00368
Create Date: 2026-06-23 14:21:25.181927

"""
from typing import Sequence, Union
import csv
import os

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36df1f56cb9e'
down_revision: Union[str, Sequence[str], None] = '5a9269d00368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_and_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    # (college, department) is the natural key. The surrogate id is assigned by CSV
    # row order at seed time, so it is only meaningful within a single database;
    # this keeps a re-seed from silently duplicating a department under a second id.
    sa.UniqueConstraint('college', 'department', name='uq_college_and_departments_college_department')
    )
    op.create_table('fields_of_science',
    sa.Column('fos_id', sa.String(length=16), nullable=False),
    sa.Column('sed_cip_title', sa.String(length=255), nullable=True),
    sa.Column('broad_field', sa.String(length=255), nullable=True),
    sa.Column('major_field', sa.String(length=255), nullable=True),
    sa.Column('detailed_field', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fos_id')
    )
    op.add_column('projects', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('college_and_department_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('fos_id', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_projects_college_and_department_id'), 'projects', ['college_and_department_id'], unique=False)
    op.create_index(op.f('ix_projects_fos_id'), 'projects', ['fos_id'], unique=False)
    op.create_foreign_key('fk_projects_college_and_department_id', 'projects', 'college_and_departments', ['college_and_department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_projects_fos_id', 'projects', 'fields_of_science', ['fos_id'], ['fos_id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed display_name from name so existing projects start with something readable
    # rather than a null, which is all the UI would otherwise have to show.
    op.execute("UPDATE projects SET display_name = name WHERE display_name IS NULL")
    # The downgrade drops the column, which removes these values.

    # ...and default it to name for new rows. A SQL DEFAULT can't reference another
    # column of the row being inserted, so the server-side equivalent is a BEFORE
    # INSERT trigger (same shape as trg_assign_lowest_unix_gid in the baseline).
    # INSERT only, matching DEFAULT semantics: an update that explicitly sets
    # display_name to null leaves it null rather than silently reinstating the slug.
    op.execute("""
        CREATE OR REPLACE FUNCTION default_project_display_name() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.display_name IS NULL THEN
                NEW.display_name := NEW.name;
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE TRIGGER trg_default_project_display_name
        BEFORE INSERT ON projects
        FOR EACH ROW EXECUTE FUNCTION default_project_display_name()
    """)

    # Seed fields_of_science from the NSF SED-CIP reference table (Table A-5,
    # nsf24300-taba-005.xlsx), exported to alembic/data/fields_of_science.csv.
    fields_of_science = sa.table(
        'fields_of_science',
        sa.column('fos_id', sa.String),
        sa.column('sed_cip_title', sa.String),
        sa.column('broad_field', sa.String),
        sa.column('major_field', sa.String),
        sa.column('detailed_field', sa.String),
    )
    csv_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'fields_of_science.csv')
    with open(csv_path, newline='', encoding='utf-8') as f:
        rows = list(csv.DictReader(f))
    if rows:
        op.bulk_insert(fields_of_science, rows)
    # The downgrade drops the table, which removes the seeded rows.

    # Seed college_and_departments from alembic/data/colleges_and_departments.csv.
    college_and_departments = sa.table(
        'college_and_departments',
        sa.column('college', sa.String),
        sa.column('department', sa.String),
    )
    cad_csv_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'colleges_and_departments.csv')
    with open(cad_csv_path, newline='', encoding='utf-8') as f:
        cad_rows = list(csv.DictReader(f))
    if cad_rows:
        op.bulk_insert(college_and_departments, cad_rows)
    # The downgrade drops the table, which removes the seeded rows.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS trg_default_project_display_name ON projects')
    op.execute('DROP FUNCTION IF EXISTS default_project_display_name()')
    op.drop_constraint('fk_projects_fos_id', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_college_and_department_id', 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_fos_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_college_and_department_id'), table_name='projects')
    op.drop_column('projects', 'fos_id')
    op.drop_column('projects', 'college_and_department_id')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'display_name')
    op.drop_table('fields_of_science')
    op.drop_table('college_and_departments')
    # ### end Alembic commands ###
