"""Add submit_nodes.group_id, drop user_submits

Revision ID: 5a9269d00368
Revises: f2ec55925c4c
Create Date: 2026-07-21 13:27:32.572229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9269d00368'
down_revision: Union[str, Sequence[str], None] = 'f2ec55925c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (submit_nodes.name, new group name) for the known active submit nodes, per
# https://github.com/CHTC/chtc-user-app-api/issues/16. Matched by name rather than id since
# submit_nodes.id values are environment-specific. Retired nodes (COSMOS, jupyter0000, osg-learn,
# osghost) and staff-only nodes (deepdivesubmit2000, annex-cm, test-ap2000) are deliberately left
# out - their submit_nodes.group_id stays NULL for now.
SUBMIT_NODE_GROUPS = [
    ('wright-ap4000.chtc.wisc.edu', 'wright-ap-login'),
    ('townsend-submit.chtc.wisc.edu', 'townsend-ap-login'),
    ('hpclogin1.chtc.wisc.edu', 'spark-login'),
    ('osg-sw-submit.chtc.wisc.edu', 'osgsw-ap-login'),
    ('oconnor-ap.chtc.wisc.edu', 'oconnor-ap-login'),
    ('learn.chtc.wisc.edu', 'learn-ap-login'),
    ('htc_transfer', 'htc-transfer-login'),
    ('ap2002.chtc.wisc.edu', 'ap2002-login'),
    ('ap2001.chtc.wisc.edu', 'ap2001-login'),
]


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit_nodes', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_submit_nodes_group_id'), 'submit_nodes', ['group_id'], unique=False)
    op.create_foreign_key('submit_nodes_group_id_fkey', 'submit_nodes', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # ### commands generated by human ###
    # Create the real Unix groups for the known active submit nodes.
    group_values = ", ".join(f"('{group_name}', FALSE)" for _, group_name in SUBMIT_NODE_GROUPS)
    op.execute(f"""
        INSERT INTO groups (name, has_groupdir)
        VALUES {group_values}
        ON CONFLICT (name) DO NOTHING
    """)

    # Point the matching submit_nodes rows at their new group.
    mapping_values = ", ".join(f"('{node_name}', '{group_name}')" for node_name, group_name in SUBMIT_NODE_GROUPS)
    op.execute(f"""
        UPDATE submit_nodes sn
        SET group_id = g.id
        FROM (VALUES {mapping_values}) AS m(node_name, group_name)
        JOIN groups g ON g.name = m.group_name
        WHERE sn.name = m.node_name
    """)

    # Backfill user_groups from user_submits before it's dropped below.
    op.execute("""
        INSERT INTO user_groups (user_id, group_id)
        SELECT DISTINCT us.user_id, sn.group_id
        FROM user_submits us
        JOIN submit_nodes sn ON sn.id = us.submit_node_id
        WHERE sn.group_id IS NOT NULL
        ON CONFLICT ON CONSTRAINT user_groups_distinct DO NOTHING
    """)

    # user_submit_nodes was created one-time by transition/post-script.sql, outside Alembic's
    # tracking (env.py excludes views from autogenerate) - it must be dropped by hand before
    # user_submits, which it depends on, can be dropped.
    op.execute("DROP VIEW IF EXISTS user_submit_nodes")

    # Drop user_submits and its indexes (moved here, ahead of the schema block above, from
    # autogenerate's original position - it has to run after the view is gone and after the
    # user_groups backfill above has had a chance to read from it).
    op.drop_index(op.f('idx_user_submits_userid_submitnodeid_incl'), table_name='user_submits', postgresql_include=['disk_quota', 'hpc_diskquota', 'hpc_inodequota', 'hpc_joblimit', 'hpc_corelimit', 'hpc_fairshare'])
    op.drop_index(op.f('ix_user_submits_id'), table_name='user_submits')
    op.drop_index(op.f('ix_user_submits_submit_node_id'), table_name='user_submits')
    op.drop_table('user_submits')

    # Recreate the view, now sourced from group membership. submit_node_id/submit_node_name
    # duplicate id/name under their old names so existing consumers of this view keep working -
    # only the quota columns, which move to their own table later, are gone.
    op.execute("""
        CREATE VIEW user_submit_nodes AS
        SELECT ug.user_id, sn.id AS submit_node_id, sn.name AS submit_node_name,
               sn.id, sn.name, sn.group_id
        FROM user_groups ug
        JOIN submit_nodes sn ON sn.group_id = ug.group_id
    """)
    # ### end commands generated by human ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands generated by human ###
    # Drop the new view before recreating what it depends on.
    op.execute("DROP VIEW IF EXISTS user_submit_nodes")
    # ### end commands generated by human ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_submits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submit_node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('for_auth_netid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('disk_quota', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hpc_diskquota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hpc_inodequota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hpc_joblimit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hpc_corelimit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hpc_fairshare', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['submit_node_id'], ['submit_nodes.id'], name=op.f('user_submits_submit_node_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_submits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_submits_pkey')),
    sa.UniqueConstraint('user_id', 'submit_node_id', 'for_auth_netid', name=op.f('user_submits_distinct'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_submits_submit_node_id'), 'user_submits', ['submit_node_id'], unique=False)
    op.create_index(op.f('ix_user_submits_id'), 'user_submits', ['id'], unique=False)
    op.create_index(op.f('idx_user_submits_userid_submitnodeid_incl'), 'user_submits', ['user_id', 'submit_node_id'], unique=False, postgresql_include=['disk_quota', 'hpc_diskquota', 'hpc_inodequota', 'hpc_joblimit', 'hpc_corelimit', 'hpc_fairshare'])
    # ### end Alembic commands ###

    # ### commands generated by human ###
    # Recreate the old view exactly as defined in transition/post-script.sql.
    op.execute("""
        CREATE VIEW user_submit_nodes AS
            SELECT DISTINCT
                us.user_id,
                us.submit_node_id,
                us.disk_quota,
                us.hpc_joblimit,
                us.hpc_corelimit,
                us.hpc_diskquota,
                us.hpc_fairshare,
                us.hpc_inodequota,
                s.name as submit_node_name
            FROM user_submits us
            JOIN submit_nodes s ON us.submit_node_id = s.id
    """)

    # Best-effort backfill of user_submits membership from user_groups. NOTE: per-user quota
    # overrides and disk_quota/for_auth_netid are NOT recoverable - upgrade() never carried them
    # forward, so this only restores membership, at the table's original default quota values.
    mapping_values = ", ".join(f"('{group_name}', '{node_name}')" for node_name, group_name in SUBMIT_NODE_GROUPS)
    op.execute(f"""
        INSERT INTO user_submits (user_id, submit_node_id, hpc_diskquota, hpc_inodequota, hpc_joblimit, hpc_corelimit, hpc_fairshare)
        SELECT DISTINCT ug.user_id, sn.id, 100, 50000, 10, 720, 100
        FROM user_groups ug
        JOIN groups g ON g.id = ug.group_id
        JOIN (VALUES {mapping_values}) AS m(group_name, node_name) ON g.name = m.group_name
        JOIN submit_nodes sn ON sn.name = m.node_name
    """)
    # ### end commands generated by human ###

    # Note: the 9 groups created in upgrade() and any membership in them are intentionally NOT
    # deleted here - groups are a general-purpose entity, and removing real Unix groups purely
    # because this migration is reverted is out of scope for a schema downgrade.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submit_nodes_group_id_fkey', 'submit_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_submit_nodes_group_id'), table_name='submit_nodes')
    op.drop_column('submit_nodes', 'group_id')
    # ### end Alembic commands ###
