"""add project_display_name to project views

Revision ID: 9b4e17c2d0a3
Revises: 36df1f56cb9e
Create Date: 2026-09-03 10:12:44.108332

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9b4e17c2d0a3'
down_revision: Union[str, Sequence[str], None] = '36df1f56cb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# projects.display_name was added in 36df1f56cb9e but only reached the /projects
# endpoints. These two views back every user-facing project list - joined_projects
# feeds /users/{id}/projects, /projects/{id}/users and UserGetFull.projects (so /me
# and /users/{id}), and pi_projects feeds /pi_projects - so without the column those
# lists can only show the slug in projects.name.
#
# project_display_name is appended after the existing select list, which is what lets
# these be CREATE OR REPLACE rather than a drop and recreate.


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands generated by human ###
    op.execute("""
        CREATE OR REPLACE VIEW joined_projects AS
            SELECT
                u.id,
                p.id AS project_id,
                p.name AS project_name,
                p.staff1 AS project_staff1,
                p.staff2 AS project_staff2,
                p.status AS project_status,
                p.last_contact AS project_last_contact,
                p.accounting_group AS project_accounting_group,
                up.is_primary AS is_primary,
                up.managed_by,
                up.created_at,
                up.updated_at,
                u.name,
                u.username,
                u.email1,
                u.email2,
                u.netid,
                u.netid_exp_datetime,
                u.phone1,
                u.phone2,
                u.is_admin,
                u.active,
                u.date,
                u.unix_uid,
                u.position,
                up.role,
                (
                    SELECT n.ticket
                    FROM notes n
                    LEFT JOIN user_notes un ON n.id = un.note_id
                    WHERE un.user_id = up.user_id AND un.project_id = up.project_id
                    ORDER BY n.id DESC
                    LIMIT 1
                ) AS last_note_ticket,
                p.display_name AS project_display_name
            FROM user_projects up
            JOIN users u ON up.user_id = u.id
            JOIN projects p ON up.project_id = p.id
    """)
    op.execute("""
        CREATE OR REPLACE VIEW pi_projects AS
        SELECT
            u.id AS user_id,
            u.name,
            u.email1,
            u.netid,
            u.phone1,
            p.id AS project_id,
            p.name AS project_name,
            p.display_name AS project_display_name
        FROM users u
        JOIN user_projects up ON up.user_id = u.id
        JOIN projects p ON p.id = up.project_id
        WHERE up.role = 'PI'
    """)
    # ### end commands generated by human ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands generated by human ###
    # CREATE OR REPLACE VIEW cannot drop a column, so these are recreated as they
    # stood before this revision (joined_projects from f2ec55925c4c, pi_projects
    # from b8ae04f033ae).
    op.execute('DROP VIEW IF EXISTS joined_projects')
    op.execute("""
        CREATE VIEW joined_projects AS
            SELECT
                u.id,
                p.id AS project_id,
                p.name AS project_name,
                p.staff1 AS project_staff1,
                p.staff2 AS project_staff2,
                p.status AS project_status,
                p.last_contact AS project_last_contact,
                p.accounting_group AS project_accounting_group,
                up.is_primary AS is_primary,
                up.managed_by,
                up.created_at,
                up.updated_at,
                u.name,
                u.username,
                u.email1,
                u.email2,
                u.netid,
                u.netid_exp_datetime,
                u.phone1,
                u.phone2,
                u.is_admin,
                u.active,
                u.date,
                u.unix_uid,
                u.position,
                up.role,
                (
                    SELECT n.ticket
                    FROM notes n
                    LEFT JOIN user_notes un ON n.id = un.note_id
                    WHERE un.user_id = up.user_id AND un.project_id = up.project_id
                    ORDER BY n.id DESC
                    LIMIT 1
                ) AS last_note_ticket
            FROM user_projects up
            JOIN users u ON up.user_id = u.id
            JOIN projects p ON up.project_id = p.id
    """)
    op.execute('DROP VIEW IF EXISTS pi_projects')
    op.execute("""
        CREATE VIEW pi_projects AS
        SELECT
            u.id AS user_id,
            u.name,
            u.email1,
            u.netid,
            u.phone1,
            p.id AS project_id,
            p.name AS project_name
        FROM users u
        JOIN user_projects up ON up.user_id = u.id
        JOIN projects p ON p.id = up.project_id
        WHERE up.role = 'PI'
    """)
    # ### end commands generated by human ###
